logging:
  level:
    org:
      springframework: info

spring:
  jackson:
    default-property-inclusion: NON_NULL
  cache:
    jcache:
      config:  ehcache3.xml

greeting:  Hello foo

timer:
  period:  2000
   